--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;

CREATE TABLE IF NOT EXISTS USERS (
    username VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
    password VARCHAR_IGNORECASE(500) NOT NULL,
    enabled BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS authorities (
    username VARCHAR_IGNORECASE(50) NOT NULL,
    authority VARCHAR_IGNORECASE(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users(username)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_username ON authorities (username, authority);
