INSERT INTO Chats DEFAULT VALUES;
INSERT INTO Chats DEFAULT VALUES;
INSERT INTO Chats DEFAULT VALUES;
INSERT INTO Chats DEFAULT VALUES;
INSERT INTO Chats DEFAULT VALUES;

INSERT INTO Messages (content, state, sender_username, chat_id)
VALUES ('test','SEND','admin',1);