CREATE TABLE IF NOT EXISTS Chats (
    id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id)
);

--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;
--INSERT INTO Chats DEFAULT VALUES;
--
----
--INSERT INTO Messages (content, state, sender_id, chat_id)
--VALUES ('test','SEND',1,1)